// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  jobId: __t.string().primaryKey().name("job_id"),
  worldId: __t.u64().name("world_id"),
  playerIdentity: __t.identity().name("player_identity"),
  targetObjectId: __t.option(__t.string()).name("target_object_id"),
  jobType: __t.string().name("job_type"),
  status: __t.string(),
  sourcePrompt: __t.string().name("source_prompt"),
  requestedAt: __t.timestamp().name("requested_at"),
  completedAt: __t.option(__t.timestamp()).name("completed_at"),
  errorCode: __t.option(__t.string()).name("error_code"),
});
