// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  voxelCoreJson: __t.string().name("voxel_core_json"),
  builderSpecJson: __t.string().name("builder_spec_json"),
  scale: __t.f64(),
  version: __t.u32(),
  updatedAt: __t.timestamp().name("updated_at"),
});
