// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  snapshotObjectId: __t.string().primaryKey().name("snapshot_object_id"),
  snapshotId: __t.string().name("snapshot_id"),
  sourceObjectId: __t.string().name("source_object_id"),
  worldId: __t.u64().name("world_id"),
  state: __t.string(),
  capturedState: __t.string().name("captured_state"),
  version: __t.u32(),
  createdBy: __t.identity().name("created_by"),
  latestEditor: __t.identity().name("latest_editor"),
  category: __t.string(),
  sizeTier: __t.string().name("size_tier"),
  sourceSpecJson: __t.string().name("source_spec_json"),
  builderSpecJson: __t.string().name("builder_spec_json"),
  positionX: __t.f64().name("position_x"),
  positionY: __t.f64().name("position_y"),
  positionZ: __t.f64().name("position_z"),
  rotationX: __t.f64().name("rotation_x"),
  rotationY: __t.f64().name("rotation_y"),
  rotationZ: __t.f64().name("rotation_z"),
  scaleX: __t.f64().name("scale_x"),
  scaleY: __t.f64().name("scale_y"),
  scaleZ: __t.f64().name("scale_z"),
  capturedAt: __t.timestamp().name("captured_at"),
});
