// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  operationId: __t.string(),
  objectId: __t.string(),
  objectVersion: __t.u32(),
  operation: __t.string(),
  rating: __t.string(),
  sourcePrompt: __t.string(),
  sourceSpecJson: __t.string(),
  builderSpecJson: __t.string(),
  modelId: __t.string(),
  promptVersion: __t.string(),
};
