// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AiJob = __t.object("AiJob", {
  jobId: __t.string(),
  worldId: __t.u64(),
  playerIdentity: __t.identity(),
  targetObjectId: __t.option(__t.string()),
  jobType: __t.string(),
  status: __t.string(),
  sourcePrompt: __t.string(),
  requestedAt: __t.timestamp(),
  completedAt: __t.option(__t.timestamp()),
  errorCode: __t.option(__t.string()),
});
export type AiJob = __Infer<typeof AiJob>;

export const ChatMessage = __t.object("ChatMessage", {
  messageId: __t.u64(),
  worldId: __t.u64(),
  senderIdentity: __t.identity(),
  senderNickname: __t.string(),
  body: __t.string(),
  createdAt: __t.timestamp(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const ObjectFeedback = __t.object("ObjectFeedback", {
  feedbackId: __t.u64(),
  worldId: __t.u64(),
  objectId: __t.string(),
  objectVersion: __t.u32(),
  operationId: __t.string(),
  operation: __t.string(),
  rating: __t.string(),
  sourcePrompt: __t.string(),
  sourceSpecJson: __t.string(),
  builderSpecJson: __t.string(),
  modelId: __t.string(),
  promptVersion: __t.string(),
  playerIdentity: __t.identity(),
  playerNickname: __t.string(),
  createdAt: __t.timestamp(),
});
export type ObjectFeedback = __Infer<typeof ObjectFeedback>;

export const ObjectLock = __t.object("ObjectLock", {
  objectId: __t.string(),
  worldId: __t.u64(),
  playerIdentity: __t.identity(),
  lockType: __t.string(),
  grantedAt: __t.timestamp(),
  expiresAtMicros: __t.option(__t.i64()),
});
export type ObjectLock = __Infer<typeof ObjectLock>;

export const PlayerAvatar = __t.object("PlayerAvatar", {
  identity: __t.identity(),
  voxelCoreJson: __t.string(),
  builderSpecJson: __t.string(),
  scale: __t.f64(),
  version: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type PlayerAvatar = __Infer<typeof PlayerAvatar>;

export const PlayerSession = __t.object("PlayerSession", {
  identity: __t.identity(),
  worldId: __t.u64(),
  connectionId: __t.option(__t.connectionId()),
  nickname: __t.string(),
  role: __t.string(),
  presenceState: __t.string(),
  positionX: __t.f64(),
  positionY: __t.f64(),
  positionZ: __t.f64(),
  rotationYaw: __t.f64(),
  rotationPitch: __t.f64(),
  joinedAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
});
export type PlayerSession = __Infer<typeof PlayerSession>;

export const SnapshotObject = __t.object("SnapshotObject", {
  snapshotObjectId: __t.string(),
  snapshotId: __t.string(),
  sourceObjectId: __t.string(),
  worldId: __t.u64(),
  state: __t.string(),
  capturedState: __t.string(),
  version: __t.u32(),
  createdBy: __t.identity(),
  latestEditor: __t.identity(),
  category: __t.string(),
  sizeTier: __t.string(),
  sourceSpecJson: __t.string(),
  builderSpecJson: __t.string(),
  positionX: __t.f64(),
  positionY: __t.f64(),
  positionZ: __t.f64(),
  rotationX: __t.f64(),
  rotationY: __t.f64(),
  rotationZ: __t.f64(),
  scaleX: __t.f64(),
  scaleY: __t.f64(),
  scaleZ: __t.f64(),
  capturedAt: __t.timestamp(),
});
export type SnapshotObject = __Infer<typeof SnapshotObject>;

export const World = __t.object("World", {
  worldId: __t.u64(),
  name: __t.string(),
  visibility: __t.string(),
  maxPlayers: __t.u32(),
  maxLiveObjects: __t.u32(),
  maxObjectsPerPlayer: __t.u32(),
  maxPendingCreateJobsPerPlayer: __t.u32(),
  destructiveEditsEnabled: __t.bool(),
  objectCooldownSeconds: __t.u32(),
  gracePeriodSeconds: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type World = __Infer<typeof World>;

export const WorldObject = __t.object("WorldObject", {
  objectId: __t.string(),
  worldId: __t.u64(),
  state: __t.string(),
  version: __t.u32(),
  createdBy: __t.identity(),
  latestEditor: __t.identity(),
  graceOwner: __t.option(__t.identity()),
  lockOwner: __t.option(__t.identity()),
  category: __t.string(),
  sizeTier: __t.string(),
  sourceSpecJson: __t.string(),
  builderSpecJson: __t.string(),
  positionX: __t.f64(),
  positionY: __t.f64(),
  positionZ: __t.f64(),
  rotationX: __t.f64(),
  rotationY: __t.f64(),
  rotationZ: __t.f64(),
  scaleX: __t.f64(),
  scaleY: __t.f64(),
  scaleZ: __t.f64(),
  graceRemainingSeconds: __t.u32(),
  cooldownRemainingSeconds: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type WorldObject = __Infer<typeof WorldObject>;

export const WorldSnapshot = __t.object("WorldSnapshot", {
  snapshotId: __t.string(),
  worldId: __t.u64(),
  cycleNumber: __t.u32(),
  reason: __t.string(),
  createdAt: __t.timestamp(),
});
export type WorldSnapshot = __Infer<typeof WorldSnapshot>;

