// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  visibility: __t.string(),
  maxPlayers: __t.u32(),
  maxLiveObjects: __t.u32(),
  maxObjectsPerPlayer: __t.u32(),
  maxPendingCreateJobsPerPlayer: __t.u32(),
  destructiveEditsEnabled: __t.bool(),
  objectCooldownSeconds: __t.u32(),
  gracePeriodSeconds: __t.u32(),
};
