// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import HeartbeatPlayerReducer from "../heartbeat_player_reducer";
import JoinWorldReducer from "../join_world_reducer";
import LeaveWorldReducer from "../leave_world_reducer";
import MovePlayerReducer from "../move_player_reducer";

export type HeartbeatPlayerParams = __Infer<typeof HeartbeatPlayerReducer>;
export type JoinWorldParams = __Infer<typeof JoinWorldReducer>;
export type LeaveWorldParams = __Infer<typeof LeaveWorldReducer>;
export type MovePlayerParams = __Infer<typeof MovePlayerReducer>;
