import {
  compileVoxelBuilderSpec,
  parseVoxelBuilderSpec,
  type VoxelBuilderSpec,
  type VoxelOp,
  type VoxelVector3,
} from "@3dvibegame/scene-authority-ts";

import type {
  AiWorkerCompletedResponse,
  AiWorkerRequest,
  CreatePlan,
  VoxelCore,
} from "./contracts";

const palettes = {
  forest: {
    primary: material("moss_stone", "#6d8860", ["primary"]),
    secondary: material("wood", "#8f6745", ["secondary"]),
    accent: material("neon", "#4de8c3", ["accent"]),
  },
  stone: {
    primary: material("moss_stone", "#8a8f98", ["primary"]),
    secondary: material("void", "#555b63", ["secondary"]),
    accent: material("glass_block", "#d3f5ff", ["accent"]),
  },
  warm: {
    primary: material("wood", "#d9822b", ["primary"]),
    secondary: material("red", "#c63a36", ["secondary"]),
    accent: material("lava_light", "#ff9a3d", ["accent"]),
  },
  cool: {
    primary: material("glass_block", "#d3f5ff", ["primary"]),
    secondary: material("cloud", "#f4f7ff", ["secondary"]),
    accent: material("neon", "#4de8c3", ["accent"]),
  },
  magic: {
    primary: material("jelly", "#ff7cb1", ["primary"]),
    secondary: material("void", "#40355e", ["secondary"]),
    accent: material("neon", "#4de8c3", ["accent"]),
  },
  neutral: {
    primary: material("cloud", "#f4f7ff", ["primary"]),
    secondary: material("wood", "#8f6745", ["secondary"]),
    accent: material("glass_block", "#d3f5ff", ["accent"]),
  },
} as const;

const sizeScale: Record<CreatePlan["size_tier"], number> = {
  tiny: 0.9,
  small: 1.2,
  medium: 1.7,
  large: 2.3,
};

export function buildCreateResponse(
  request: AiWorkerRequest,
  plan: CreatePlan,
  warnings: string[] = [],
): AiWorkerCompletedResponse {
  const spec = buildVoxelSpec(request, plan, warnings);
  const sourceSpec = parseVoxelBuilderSpec(spec);
  const builderSpec = compileVoxelBuilderSpec(sourceSpec);
  const baseId = `${slug(plan.object_category)}_${shortHash(request.source_prompt)}`;

  return {
    status: "completed",
    job_id_base: `${baseId}_job`,
    object_id_base: `${baseId}_object`,
    source_spec: sourceSpec,
    builder_spec: builderSpec,
    warnings,
  };
}

// --- Direct-voxel path: the LLM authors the operations ---------------------

/**
 * Wraps an LLM-authored voxel core (object metadata + operations) into a full
 * VoxelBuilderSpec envelope. The deterministic fields (ids, grid, placement,
 * anchors, compile hints) are filled here so the LLM only has to author geometry.
 * Operations are placed as-is and validated downstream by parseVoxelBuilderSpec.
 */
export function assembleVoxelSpec(
  sourcePrompt: string,
  core: VoxelCore,
  warnings: string[] = [],
): VoxelBuilderSpec {
  const baseId = `${slug(core.object_category)}_${shortHash(sourcePrompt)}`;

  return {
    spec_version: "0.1",
    request_id: `${baseId}::prompt_0`,
    intent_id: `${baseId}::intent_0`,
    operation: "create",
    target_object_id: null,
    base_object_version: null,
    object_category: slug(core.object_category),
    size_tier: core.size_tier,
    style_tags: unique(core.style_tags.map(slug)).slice(0, 6),
    behaviors: unique(core.behaviors.map(slug)).slice(0, 3),
    grid: {
      unit_meters: 0.5,
      up_axis: "y",
      rotation_step_degrees: 90,
    },
    placement: {
      mode: "absolute",
      reference_object: null,
      relation: null,
      offset: [0, 0, 0],
    },
    materials: core.materials.map((entry) => ({
      material_id: entry.material_id,
      label: entry.material_id,
      render_class: "matte_voxel",
      color_hint: entry.color_hint,
      tags: entry.tags,
    })),
    anchors: [
      { anchor_id: "base", position: [0, 0, 0], tags: ["placement"] },
      { anchor_id: "focus", position: [0, 2.4, 0], tags: ["camera"] },
    ],
    // Validated as VoxelOp[] by parseVoxelBuilderSpec in buildVoxelResponse.
    operations: core.operations as VoxelOp[],
    compile_hints: {
      preferred_runtime: "primitive_parts",
      preserve_edit_regions: true,
      collision_detail: "coarse",
    },
    diagnostics: ["generated by voxel-builder ai worker", ...warnings],
  };
}

/**
 * Validates an LLM-authored voxel core, grounds it to the floor, and compiles it.
 * Mirrors buildCreateResponse but takes operations from the LLM instead of a template.
 */
export function buildVoxelResponse(
  request: AiWorkerRequest,
  core: VoxelCore,
  warnings: string[] = [],
): AiWorkerCompletedResponse {
  const candidate = assembleVoxelSpec(request.source_prompt, core, warnings);
  const parsed = parseVoxelBuilderSpec(candidate);
  const grounded: VoxelBuilderSpec = {
    ...parsed,
    operations: groundOperations(parsed.operations),
  };
  const builderSpec = compileVoxelBuilderSpec(grounded);
  const baseId = `${slug(core.object_category)}_${shortHash(request.source_prompt)}`;

  return {
    status: "completed",
    job_id_base: `${baseId}_job`,
    object_id_base: `${baseId}_object`,
    source_spec: grounded,
    builder_spec: builderSpec,
    warnings,
  };
}

// --- Template path (fixture / no-key fallback) -----------------------------

export function buildVoxelSpec(
  request: AiWorkerRequest,
  plan: CreatePlan,
  warnings: string[] = [],
): VoxelBuilderSpec {
  const baseId = `${slug(plan.object_category)}_${shortHash(request.source_prompt)}`;
  const palette = palettes[plan.palette];
  const scale = sizeScale[plan.size_tier];
  const materialIds = {
    primary: palette.primary.material_id,
    secondary: palette.secondary.material_id,
    accent: palette.accent.material_id,
  };
  const operations = groundOperations(operationsForPlan(plan, scale, materialIds));

  return {
    spec_version: "0.1",
    request_id: `${baseId}::prompt_0`,
    intent_id: `${baseId}::intent_0`,
    operation: "create",
    target_object_id: null,
    base_object_version: null,
    object_category: slug(plan.object_category),
    size_tier: plan.size_tier,
    style_tags: unique(plan.style_tags.map(slug)).slice(0, 6),
    behaviors: unique(plan.behaviors.map(slug)).slice(0, 3),
    grid: {
      unit_meters: 0.5,
      up_axis: "y",
      rotation_step_degrees: 90,
    },
    placement: {
      mode: "absolute",
      reference_object: null,
      relation: null,
      offset: [0, 0, 0],
    },
    materials: [palette.primary, palette.secondary, palette.accent],
    anchors: [
      { anchor_id: "base", position: [0, 0, 0], tags: ["placement"] },
      { anchor_id: "focus", position: [0, 2 * scale, 0], tags: ["camera"] },
    ],
    operations,
    compile_hints: {
      preferred_runtime: "primitive_parts",
      preserve_edit_regions: true,
      collision_detail: "coarse",
    },
    diagnostics: [
      `generated by create-only ai worker from ${plan.shape} plan`,
      ...warnings,
      ...plan.key_features.slice(0, 3).map((feature) => `feature: ${feature}`),
    ],
  };
}

function operationsForPlan(
  plan: CreatePlan,
  scale: number,
  materials: { primary: string; secondary: string; accent: string },
): VoxelOp[] {
  if (plan.shape === "tree" || plan.object_category.toLowerCase().includes("tree")) {
    return [
      box(
        "trunk",
        [0, 0.8 * scale, 0],
        [0.35 * scale, 1.6 * scale, 0.35 * scale],
        materials.secondary,
        ["trunk"],
      ),
      sphere("canopy_low", [0, 1.75 * scale, 0], 0.95 * scale, materials.primary, [
        "foliage",
      ]),
      sphere("canopy_high", [0, 2.45 * scale, 0], 0.65 * scale, materials.primary, [
        "foliage",
      ]),
      sphere("glow", [0.45 * scale, 2.2 * scale, 0.1 * scale], 0.16 * scale, materials.accent, [
        "detail",
        "soft_glow",
      ]),
    ];
  }

  if (plan.shape === "structure") {
    return [
      box(
        "base",
        [0, 0.5 * scale, 0],
        [1.5 * scale, 1 * scale, 1.2 * scale],
        materials.primary,
        ["body"],
      ),
      box(
        "roof",
        [0, 1.2 * scale, 0],
        [1.8 * scale, 0.35 * scale, 1.4 * scale],
        materials.secondary,
        ["roof"],
      ),
      box(
        "door",
        [0, 0.35 * scale, 0.62 * scale],
        [0.35 * scale, 0.6 * scale, 0.08 * scale],
        materials.accent,
        ["detail"],
      ),
    ];
  }

  if (plan.shape === "creature") {
    return [
      sphere("body", [0, 0.9 * scale, 0], 0.7 * scale, materials.primary, ["body"]),
      sphere("head", [0, 1.65 * scale, 0.12 * scale], 0.42 * scale, materials.primary, ["head"]),
      line(
        "left_leg",
        [-0.25 * scale, 0.25 * scale, 0],
        [-0.45 * scale, 0, 0],
        0.08 * scale,
        materials.secondary,
        ["leg"],
      ),
      line(
        "right_leg",
        [0.25 * scale, 0.25 * scale, 0],
        [0.45 * scale, 0, 0],
        0.08 * scale,
        materials.secondary,
        ["leg"],
      ),
      sphere(
        "accent",
        [0.18 * scale, 1.72 * scale, 0.46 * scale],
        0.09 * scale,
        materials.accent,
        ["detail", "soft_glow"],
      ),
    ];
  }

  if (plan.shape === "cluster") {
    return [
      sphere("cluster_a", [-0.45 * scale, 0.55 * scale, 0], 0.55 * scale, materials.primary, [
        "cluster",
      ]),
      sphere(
        "cluster_b",
        [0.35 * scale, 0.75 * scale, 0.15 * scale],
        0.7 * scale,
        materials.secondary,
        ["cluster"],
      ),
      sphere(
        "cluster_c",
        [0.05 * scale, 1.15 * scale, -0.25 * scale],
        0.42 * scale,
        materials.accent,
        ["detail"],
      ),
    ];
  }

  return [
    box(
      "body",
      [0, 0.55 * scale, 0],
      [1 * scale, 1.1 * scale, 1 * scale],
      materials.primary,
      ["body"],
    ),
    box(
      "cap",
      [0, 1.25 * scale, 0],
      [0.75 * scale, 0.35 * scale, 0.75 * scale],
      materials.secondary,
      ["top"],
    ),
    sphere("accent", [0.35 * scale, 1.45 * scale, 0.35 * scale], 0.16 * scale, materials.accent, [
      "detail",
    ]),
  ];
}

function groundOperations(operations: VoxelOp[]) {
  const minY = operations.reduce(
    (lowest, operation) => Math.min(lowest, minOperationY(operation)),
    0,
  );
  if (minY >= 0) {
    return operations;
  }
  return operations.map((operation) => translateOperationY(operation, -minY));
}

function minOperationY(operation: VoxelOp) {
  switch (operation.kind) {
    case "add_box":
      return operation.position[1] - operation.size[1] / 2;
    case "add_sphere":
      return operation.center[1] - operation.radius;
    case "add_line":
      return Math.min(operation.from[1], operation.to[1]) - operation.radius;
    default:
      return 0;
  }
}

function translateOperationY(operation: VoxelOp, offsetY: number): VoxelOp {
  switch (operation.kind) {
    case "add_box":
      return { ...operation, position: translateY(operation.position, offsetY) };
    case "add_sphere":
      return { ...operation, center: translateY(operation.center, offsetY) };
    case "add_line":
      return {
        ...operation,
        from: translateY(operation.from, offsetY),
        to: translateY(operation.to, offsetY),
      };
    default:
      return operation;
  }
}

function translateY(vector: VoxelVector3, offsetY: number): VoxelVector3 {
  return [vector[0], vector[1] + offsetY, vector[2]];
}

function material(material_id: string, color_hint: string, tags: string[]) {
  return {
    material_id,
    label: material_id,
    render_class: "matte_voxel",
    color_hint,
    tags,
  };
}

function box(
  op_id: string,
  position: VoxelVector3,
  size: VoxelVector3,
  material_id: string,
  tags: string[],
): VoxelOp {
  return { op_id, kind: "add_box", mode: "union", position, size, material_id, tags };
}

function sphere(
  op_id: string,
  center: VoxelVector3,
  radius: number,
  material_id: string,
  tags: string[],
): VoxelOp {
  return { op_id, kind: "add_sphere", mode: "union", center, radius, material_id, tags };
}

function line(
  op_id: string,
  from: VoxelVector3,
  to: VoxelVector3,
  radius: number,
  material_id: string,
  tags: string[],
): VoxelOp {
  return {
    op_id,
    kind: "add_line",
    mode: "union",
    from,
    to,
    radius,
    shape: "rounded",
    material_id,
    tags,
  };
}

function shortHash(value: string) {
  let hash = 0x811c9dc5;
  for (let index = 0; index < value.length; index += 1) {
    hash ^= value.charCodeAt(index);
    hash = Math.imul(hash, 0x01000193);
  }
  return (hash >>> 0).toString(16).padStart(8, "0");
}

function slug(value: string) {
  return (
    value
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "")
      .slice(0, 40) || "object"
  );
}

function unique(values: string[]) {
  return [...new Set(values.filter(Boolean))];
}
