import {
  compileVoxelBuilderSpec,
  parseVoxelBuilderSpec,
  type VoxelBuilderSpec,
  type VoxelOp,
  type VoxelVector3,
} from "@3dvibegame/scene-authority-ts";
import { createHash } from "node:crypto";

import type {
  AiWorkerCompletedResponse,
  AiWorkerRequest,
  CreatePlan,
} from "./contracts.ts";

const palettes = {
  forest: { primary: "#2f7d46", secondary: "#7a4f2a", accent: "#9be564" },
  stone: { primary: "#8a8f98", secondary: "#555b63", accent: "#c9d1d9" },
  warm: { primary: "#d9822b", secondary: "#8f4a21", accent: "#ffd166" },
  cool: { primary: "#4f8cc9", secondary: "#2f5d7c", accent: "#9ad7ff" },
  magic: { primary: "#7c5cff", secondary: "#35206b", accent: "#f3a6ff" },
  neutral: { primary: "#a99f8f", secondary: "#61584d", accent: "#f0e6d2" },
} as const;

const sizeScale: Record<CreatePlan["size_tier"], number> = {
  tiny: 0.7,
  small: 1,
  medium: 1.35,
  large: 1.75,
};

export function buildCreateResponse(
  request: AiWorkerRequest,
  plan: CreatePlan,
  warnings: string[] = [],
): AiWorkerCompletedResponse {
  const spec = buildVoxelSpec(request, plan, warnings);
  const sourceSpec = parseVoxelBuilderSpec(spec);
  const builderSpec = compileVoxelBuilderSpec(sourceSpec);
  const baseId = `${slug(plan.object_category)}_${shortHash(request.source_prompt)}`;

  return {
    status: "completed",
    job_id_base: `${baseId}_job`,
    object_id_base: `${baseId}_object`,
    source_spec: sourceSpec,
    builder_spec: builderSpec,
    warnings,
  };
}

function buildVoxelSpec(
  request: AiWorkerRequest,
  plan: CreatePlan,
  warnings: string[],
): VoxelBuilderSpec {
  const baseId = `${slug(plan.object_category)}_${shortHash(request.source_prompt)}`;
  const palette = palettes[plan.palette];
  const scale = sizeScale[plan.size_tier];

  return {
    spec_version: "0.1",
    request_id: `${baseId}::prompt_0`,
    intent_id: `${baseId}::intent_0`,
    operation: "create",
    target_object_id: null,
    base_object_version: null,
    object_category: slug(plan.object_category),
    size_tier: plan.size_tier,
    style_tags: unique(plan.style_tags.map(slug)).slice(0, 6),
    behaviors: unique(plan.behaviors.map(slug)).slice(0, 3),
    grid: {
      unit_meters: 0.25,
      up_axis: "y",
      rotation_step_degrees: 90,
    },
    placement: {
      mode: "absolute",
      reference_object: null,
      relation: null,
      offset: [0, 0, 0],
    },
    materials: [
      material("primary", palette.primary, ["primary"]),
      material("secondary", palette.secondary, ["secondary"]),
      material("accent", palette.accent, ["accent"]),
    ],
    anchors: [
      { anchor_id: "base", position: [0, 0, 0], tags: ["placement"] },
      { anchor_id: "focus", position: [0, 2 * scale, 0], tags: ["camera"] },
    ],
    operations: operationsForPlan(plan, scale),
    compile_hints: {
      preferred_runtime: "primitive_parts",
      preserve_edit_regions: true,
      collision_detail: "coarse",
    },
    diagnostics: [
      `generated by create-only ai worker from ${plan.shape} plan`,
      ...warnings,
      ...plan.key_features.slice(0, 3).map((feature) => `feature: ${feature}`),
    ],
  };
}

function operationsForPlan(plan: CreatePlan, scale: number): VoxelOp[] {
  if (plan.shape === "tree" || plan.object_category.toLowerCase().includes("tree")) {
    return [
      box(
        "trunk",
        [0, 0.8 * scale, 0],
        [0.35 * scale, 1.6 * scale, 0.35 * scale],
        "secondary",
        ["trunk"],
      ),
      sphere("canopy_low", [0, 1.75 * scale, 0], 0.95 * scale, "primary", ["foliage"]),
      sphere("canopy_high", [0, 2.45 * scale, 0], 0.65 * scale, "primary", ["foliage"]),
      sphere("glow", [0.45 * scale, 2.2 * scale, 0.1 * scale], 0.16 * scale, "accent", [
        "detail",
      ]),
    ];
  }

  if (plan.shape === "structure") {
    return [
      box("base", [0, 0.5 * scale, 0], [1.5 * scale, 1 * scale, 1.2 * scale], "primary", [
        "body",
      ]),
      box(
        "roof",
        [0, 1.2 * scale, 0],
        [1.8 * scale, 0.35 * scale, 1.4 * scale],
        "secondary",
        ["roof"],
      ),
      box(
        "door",
        [0, 0.35 * scale, 0.62 * scale],
        [0.35 * scale, 0.6 * scale, 0.08 * scale],
        "accent",
        ["detail"],
      ),
    ];
  }

  if (plan.shape === "creature") {
    return [
      sphere("body", [0, 0.9 * scale, 0], 0.7 * scale, "primary", ["body"]),
      sphere("head", [0, 1.65 * scale, 0.12 * scale], 0.42 * scale, "primary", ["head"]),
      line(
        "left_leg",
        [-0.25 * scale, 0.25 * scale, 0],
        [-0.45 * scale, 0, 0],
        0.08 * scale,
        "secondary",
        ["leg"],
      ),
      line(
        "right_leg",
        [0.25 * scale, 0.25 * scale, 0],
        [0.45 * scale, 0, 0],
        0.08 * scale,
        "secondary",
        ["leg"],
      ),
      sphere("accent", [0.18 * scale, 1.72 * scale, 0.46 * scale], 0.09 * scale, "accent", ["detail"]),
    ];
  }

  if (plan.shape === "cluster") {
    return [
      sphere("cluster_a", [-0.45 * scale, 0.55 * scale, 0], 0.55 * scale, "primary", [
        "cluster",
      ]),
      sphere(
        "cluster_b",
        [0.35 * scale, 0.75 * scale, 0.15 * scale],
        0.7 * scale,
        "secondary",
        ["cluster"],
      ),
      sphere(
        "cluster_c",
        [0.05 * scale, 1.15 * scale, -0.25 * scale],
        0.42 * scale,
        "accent",
        ["detail"],
      ),
    ];
  }

  return [
    box("body", [0, 0.55 * scale, 0], [1 * scale, 1.1 * scale, 1 * scale], "primary", ["body"]),
    box(
      "cap",
      [0, 1.25 * scale, 0],
      [0.75 * scale, 0.35 * scale, 0.75 * scale],
      "secondary",
      ["top"],
    ),
    sphere("accent", [0.35 * scale, 1.45 * scale, 0.35 * scale], 0.16 * scale, "accent", [
      "detail",
    ]),
  ];
}

function material(material_id: string, color_hint: string, tags: string[]) {
  return {
    material_id,
    label: material_id,
    render_class: "matte_voxel",
    color_hint,
    tags,
  };
}

function box(
  op_id: string,
  position: VoxelVector3,
  size: VoxelVector3,
  material_id: string,
  tags: string[],
): VoxelOp {
  return { op_id, kind: "add_box", mode: "union", position, size, material_id, tags };
}

function sphere(
  op_id: string,
  center: VoxelVector3,
  radius: number,
  material_id: string,
  tags: string[],
): VoxelOp {
  return { op_id, kind: "add_sphere", mode: "union", center, radius, material_id, tags };
}

function line(
  op_id: string,
  from: VoxelVector3,
  to: VoxelVector3,
  radius: number,
  material_id: string,
  tags: string[],
): VoxelOp {
  return {
    op_id,
    kind: "add_line",
    mode: "union",
    from,
    to,
    radius,
    shape: "rounded",
    material_id,
    tags,
  };
}

function shortHash(value: string) {
  return createHash("sha1").update(value).digest("hex").slice(0, 8);
}

function slug(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 40) || "object";
}

function unique(values: string[]) {
  return [...new Set(values.filter(Boolean))];
}
