// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  objectId: __t.string().primaryKey().name("object_id"),
  worldId: __t.u64().name("world_id"),
  playerIdentity: __t.identity().name("player_identity"),
  lockType: __t.string().name("lock_type"),
  grantedAt: __t.timestamp().name("granted_at"),
  expiresAtMicros: __t.option(__t.i64()).name("expires_at_micros"),
});
