// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  worldId: __t.u64().name("world_id"),
  connectionId: __t.option(__t.connectionId()).name("connection_id"),
  nickname: __t.string(),
  role: __t.string(),
  presenceState: __t.string().name("presence_state"),
  positionX: __t.f64().name("position_x"),
  positionY: __t.f64().name("position_y"),
  positionZ: __t.f64().name("position_z"),
  rotationYaw: __t.f64().name("rotation_yaw"),
  rotationPitch: __t.f64().name("rotation_pitch"),
  joinedAt: __t.timestamp().name("joined_at"),
  lastSeenAt: __t.timestamp().name("last_seen_at"),
});
