// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const PlayerSession = __t.object("PlayerSession", {
  identity: __t.identity(),
  worldId: __t.u64(),
  connectionId: __t.option(__t.connectionId()),
  nickname: __t.string(),
  role: __t.string(),
  presenceState: __t.string(),
  positionX: __t.f64(),
  positionY: __t.f64(),
  positionZ: __t.f64(),
  rotationYaw: __t.f64(),
  rotationPitch: __t.f64(),
  joinedAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
});
export type PlayerSession = __Infer<typeof PlayerSession>;

export const World = __t.object("World", {
  worldId: __t.u64(),
  name: __t.string(),
  visibility: __t.string(),
  maxPlayers: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type World = __Infer<typeof World>;
