// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  worldId: __t.u64().primaryKey().name("world_id"),
  name: __t.string(),
  visibility: __t.string(),
  maxPlayers: __t.u32().name("max_players"),
  maxLiveObjects: __t.u32().name("max_live_objects"),
  maxObjectsPerPlayer: __t.u32().name("max_objects_per_player"),
  maxPendingCreateJobsPerPlayer: __t.u32().name("max_pending_create_jobs_per_player"),
  destructiveEditsEnabled: __t.bool().name("destructive_edits_enabled"),
  objectCooldownSeconds: __t.u32().name("object_cooldown_seconds"),
  gracePeriodSeconds: __t.u32().name("grace_period_seconds"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
