// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  objectId: __t.string().primaryKey().name("object_id"),
  worldId: __t.u64().name("world_id"),
  state: __t.string(),
  version: __t.u32(),
  createdBy: __t.identity().name("created_by"),
  latestEditor: __t.identity().name("latest_editor"),
  graceOwner: __t.option(__t.identity()).name("grace_owner"),
  lockOwner: __t.option(__t.identity()).name("lock_owner"),
  category: __t.string(),
  sizeTier: __t.string().name("size_tier"),
  builderSpecJson: __t.string().name("builder_spec_json"),
  positionX: __t.f64().name("position_x"),
  positionY: __t.f64().name("position_y"),
  positionZ: __t.f64().name("position_z"),
  rotationX: __t.f64().name("rotation_x"),
  rotationY: __t.f64().name("rotation_y"),
  rotationZ: __t.f64().name("rotation_z"),
  scaleX: __t.f64().name("scale_x"),
  scaleY: __t.f64().name("scale_y"),
  scaleZ: __t.f64().name("scale_z"),
  graceRemainingSeconds: __t.u32().name("grace_remaining_seconds"),
  cooldownRemainingSeconds: __t.u32().name("cooldown_remaining_seconds"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
