// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CancelEditReducer from "../cancel_edit_reducer";
import CreateSnapshotReducer from "../create_snapshot_reducer";
import CreateWorldReducer from "../create_world_reducer";
import DeleteChatMessageReducer from "../delete_chat_message_reducer";
import DeleteObjectReducer from "../delete_object_reducer";
import ExpireAiJobReducer from "../expire_ai_job_reducer";
import ExpireCooldownReducer from "../expire_cooldown_reducer";
import ExpireEditLockReducer from "../expire_edit_lock_reducer";
import ExpireGracePeriodReducer from "../expire_grace_period_reducer";
import FailAiJobReducer from "../fail_ai_job_reducer";
import HeartbeatPlayerReducer from "../heartbeat_player_reducer";
import JoinWorldReducer from "../join_world_reducer";
import JoinWorldByIdReducer from "../join_world_by_id_reducer";
import LeaveWorldReducer from "../leave_world_reducer";
import MovePlayerReducer from "../move_player_reducer";
import ReleaseObjectReducer from "../release_object_reducer";
import RequestCreateObjectReducer from "../request_create_object_reducer";
import RequestEditLockReducer from "../request_edit_lock_reducer";
import ResetWorldReducer from "../reset_world_reducer";
import SendChatMessageReducer from "../send_chat_message_reducer";
import SetPlayerRoleReducer from "../set_player_role_reducer";
import SubmitAiDraftReducer from "../submit_ai_draft_reducer";
import SubmitObjectEditReducer from "../submit_object_edit_reducer";
import UpdateDraftTransformReducer from "../update_draft_transform_reducer";
import UpdateLockedTransformReducer from "../update_locked_transform_reducer";
import UpdateWorldSettingsReducer from "../update_world_settings_reducer";

export type CancelEditParams = __Infer<typeof CancelEditReducer>;
export type CreateSnapshotParams = __Infer<typeof CreateSnapshotReducer>;
export type CreateWorldParams = __Infer<typeof CreateWorldReducer>;
export type DeleteChatMessageParams = __Infer<typeof DeleteChatMessageReducer>;
export type DeleteObjectParams = __Infer<typeof DeleteObjectReducer>;
export type ExpireAiJobParams = __Infer<typeof ExpireAiJobReducer>;
export type ExpireCooldownParams = __Infer<typeof ExpireCooldownReducer>;
export type ExpireEditLockParams = __Infer<typeof ExpireEditLockReducer>;
export type ExpireGracePeriodParams = __Infer<typeof ExpireGracePeriodReducer>;
export type FailAiJobParams = __Infer<typeof FailAiJobReducer>;
export type HeartbeatPlayerParams = __Infer<typeof HeartbeatPlayerReducer>;
export type JoinWorldParams = __Infer<typeof JoinWorldReducer>;
export type JoinWorldByIdParams = __Infer<typeof JoinWorldByIdReducer>;
export type LeaveWorldParams = __Infer<typeof LeaveWorldReducer>;
export type MovePlayerParams = __Infer<typeof MovePlayerReducer>;
export type ReleaseObjectParams = __Infer<typeof ReleaseObjectReducer>;
export type RequestCreateObjectParams = __Infer<typeof RequestCreateObjectReducer>;
export type RequestEditLockParams = __Infer<typeof RequestEditLockReducer>;
export type ResetWorldParams = __Infer<typeof ResetWorldReducer>;
export type SendChatMessageParams = __Infer<typeof SendChatMessageReducer>;
export type SetPlayerRoleParams = __Infer<typeof SetPlayerRoleReducer>;
export type SubmitAiDraftParams = __Infer<typeof SubmitAiDraftReducer>;
export type SubmitObjectEditParams = __Infer<typeof SubmitObjectEditReducer>;
export type UpdateDraftTransformParams = __Infer<typeof UpdateDraftTransformReducer>;
export type UpdateLockedTransformParams = __Infer<typeof UpdateLockedTransformReducer>;
export type UpdateWorldSettingsParams = __Infer<typeof UpdateWorldSettingsReducer>;

